apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate-jet-authtls.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: jet
      namespace: jet-system
    path: patch-jet-deployment.yaml
